@echo off
echo Limpiando node_modules...
rmdir /s /q node_modules
echo Limpiando package-lock.json...
del package-lock.json
echo Instalando dependencias...
npm install
echo Iniciando la aplicación...
npm start
